import type { IconDefinition } from '@fortawesome/fontawesome-svg-core'
import {
  faHouse,
  faMagnifyingGlass,
  faFileLines,
  faComment,
  faUser,
  faUsers,
  faHandshake,
  faBell,
  faPlus,
  faMinus,
  faXmark,
  faEllipsisVertical,
  faEllipsis,
  faCheck,
  faCheckDouble,
  faCircleCheck,
  faPen,
  faChevronRight,
  faChevronLeft,
  faChevronDown,
  faArrowLeft,
  faArrowRight,
  faPaperPlane,
  faLocationDot,
  faLocationCrosshairs,
  faStar as faStarSolid,
  faShieldHalved,
  faFlag,
  faBan,
  faTag,
  faGift,
  faMoneyBillTransfer,
  faSackDollar,
  faClock,
  faCalendarDays,
  faHourglassHalf,
  faTriangleExclamation,
  faCircleExclamation,
  faCreditCard,
  faIdCard,
  faFlagCheckered,
  faBullseye,
  faGauge,
  faScroll,
  faGear,
  faMobileScreenButton,
  faLock,
  faEye,
  faEyeSlash,
  faTrash,
  faShareNodes,
  faBookmark as faBookmarkSolid,
  faHeart as faHeartSolid,
  faCamera,
  faImage,
  faFilter,
  faArrowUpWideShort,
  faSpinner,
  faCircleInfo,
  faCirclePlus,
  faGamepad,
  faPersonRunning,
  faUtensils,
  faFilm,
  faPersonWalking,
  faMugSaucer,
  faPlaneDeparture,
  faBook,
  faPalette,
  faClipboardList,
  faRightFromBracket,
  faGraduationCap,
  faLaptopCode,
  faBriefcase,
  faHandHoldingHeart,
  faChess,
} from '@fortawesome/free-solid-svg-icons'
import { faStar as faStarRegular, faBookmark as faBookmarkRegular, faHeart as faHeartRegular } from '@fortawesome/free-regular-svg-icons'

/**
 * Central icon registry: semantic name -> FontAwesome icon. Views/components
 * should import `icons` and reference it by name rather than importing FA
 * icons directly, so the whole app's iconography can be swapped from here.
 */
export const icons = {
  home: faHouse,
  explore: faMagnifyingGlass,
  applications: faFileLines,
  chat: faComment,
  profile: faUser,
  people: faUsers,
  brand: faHandshake,
  notifications: faBell,
  add: faPlus,
  remove: faMinus,
  close: faXmark,
  menu: faEllipsisVertical,
  more: faEllipsis,
  check: faCheck,
  checkDouble: faCheckDouble,
  verified: faCircleCheck,
  edit: faPen,
  chevronRight: faChevronRight,
  chevronLeft: faChevronLeft,
  chevronDown: faChevronDown,
  back: faArrowLeft,
  forward: faArrowRight,
  send: faPaperPlane,
  location: faLocationDot,
  locateMe: faLocationCrosshairs,
  starSolid: faStarSolid,
  starOutline: faStarRegular,
  trust: faShieldHalved,
  report: faFlag,
  block: faBan,
  priceTag: faTag,
  /** The category vocabulary itself, as opposed to any one category's glyph. */
  category: faTag,
  free: faGift,
  ownerPays: faMoneyBillTransfer,
  amount: faSackDollar,
  time: faClock,
  date: faCalendarDays,
  pending: faHourglassHalf,
  warning: faTriangleExclamation,
  error: faCircleExclamation,
  payment: faCreditCard,
  identity: faIdCard,
  completedFlag: faFlagCheckered,
  today: faBullseye,
  dashboard: faGauge,
  auditLog: faScroll,
  settings: faGear,
  phone: faMobileScreenButton,
  lock: faLock,
  show: faEye,
  hide: faEyeSlash,
  delete: faTrash,
  share: faShareNodes,
  bookmarkSolid: faBookmarkSolid,
  bookmarkOutline: faBookmarkRegular,
  heartSolid: faHeartSolid,
  heartOutline: faHeartRegular,
  camera: faCamera,
  image: faImage,
  filter: faFilter,
  sort: faArrowUpWideShort,
  spinner: faSpinner,
  info: faCircleInfo,
  createActivity: faCirclePlus,
  activities: faClipboardList,
  logout: faRightFromBracket,
} satisfies Record<string, IconDefinition>

export type IconName = keyof typeof icons

const categoryIcons: Record<string, IconDefinition> = {
  gaming: faGamepad,
  sport: faPersonRunning,
  food: faUtensils,
  cinema: faFilm,
  walk: faPersonWalking,
  coffee: faMugSaucer,
  travel: faPlaneDeparture,
  study: faBook,

  // The roots added in 11.5. Without these the six new shelves all render the
  // same generic glyph, which reads as "unknown" rather than as a category.
  education: faGraduationCap,
  technology: faLaptopCode,
  creative: faPalette,
  business: faBriefcase,
  hobbies: faChess,
  community: faHandHoldingHeart,
}

/** Category icon by slug, falling back to a generic "more" glyph for unmapped/future categories. */
export function categoryIcon(slug: string): IconDefinition {
  return categoryIcons[slug] ?? faEllipsis
}
